name: Ubuntu
on:
  push:
    branches:
      main
  #watch:
  #  types: started
jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: SSH connection to Actions
      uses: csexton/debugger-action@master
