name: Windows
on:
  workflow_dispatch:
  #watch:
  #  types: started
jobs:
  Ubuntu:
    runs-on: windows-latest
    steps:
    - name: SSH connection to Actions
      uses: zxunge/debugger-action@master
